apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: bamboo
  labels:
    app: pgsql
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: pgsql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  namespace: bamboo
spec:
  serviceName: "pgsql"
  replicas: 3
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
      - name: pgsql
        image: postgres:13
        ports:
        - containerPort: 5432
          name: pgsql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-password
              key: password
        volumeMounts:
        - name: pgsql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgsql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-sc"
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: pgsql-password
  namespace: bamboo
type: Opaque
data:
  password: cG9zdGdyZXM=  # Este es un ejemplo, reemplaza 'cG9zdGdyZXM=' con tu contraseña codificada en base64.
