apiVersion: v1
kind: Pod
metadata:
  name: postgres-client-pod
  namespace: bamboo
spec:
  containers:
    - name: postgres-client
      image: postgres:latest
      command: ["psql"]
      args: ["-h", "bitbucketdb.cyixla73xfrd.us-east-1.rds.amazonaws.com", "-U", "bitbucket", "-d", "bitbucket", "-W", "Xl992lu3Htx]2j2]fMOQZ-]i~+hK"]
      tty: true
  restartPolicy: Never