apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: bitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: bitbucket
        - name: POSTGRES_PASSWORD
          value: sduejsduifsjkdkj
        - name: POSTGRES_DB
          value: bitbucket
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-pvc
        persistentVolumeClaim:
          claimName: bitbucket-efs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: bitbucket
spec:
  selector:
    app: postgresql
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-efs-pvc
  namespace: bitbucket
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitbucket-efs-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09f65fe81316d211e::fsap-073cd0d2be9f8b44a