AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para crear un cluster de Redis

Mappings:
  ClusterNames:
    sandbox:
      Name: "elasticache-redis-cluster-pagopension-sandbox"
    dev:
      Name: "elasticache-redis-cluster-pagopension-dev"
    qa: 
      Name: "elasticache-redis-cluster-pagopension-qa"
    prod:
      Name: "elasticache-redis-cluster-pagopension-prod"

Parameters:

  Entorno:
    Description: El entorno donde se desplegarán los recursos (sandbox, dev, qa, prod)
    Type: String
    Default: sandbox
    AllowedValues:
      - sandbox
      - dev
      - qa
      - prod

  RedisSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for Redis subnetgroup

  RedisVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for Redis security group

  CidrIp:
    Type: String
    Description: IP range VPC/Subnet for Redis security group
    
  CidrIp2:
    Type: String
    Description: IP range Pod for Redis security group
  
  
  SetCacheNodeType:
    Type: String
    Description: Redis node type https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html
    Default: cache.t2.micro
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium

      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium

      - cache.t4g.micro
      - cache.t4g.small
      - cache.t4g.medium

      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge

      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m5.24xlarge

      - cache.m6g.large
      - cache.m6g.xlarge
      - cache.m6g.2xlarge
      - cache.m6g.4xlarge
      - cache.m6g.8xlarge
      - cache.m6g.12xlarge
      - cache.m6g.16xlarge
    
      - cache.m7g.large
      - cache.m7g.xlarge
      - cache.m7g.2xlarge
      - cache.m7g.4xlarge
      - cache.m7g.8xlarge
      - cache.m7g.12xlarge
      - cache.m7g.16xlarge

      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge

      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r5.24xlarge

      - cache.r6g.large
      - cache.r6g.xlarge
      - cache.r6g.2xlarge
      - cache.r6g.4xlarge
      - cache.r6g.8xlarge
      - cache.r6g.12xlarge
      - cache.r6g.16xlarge

      - cache.r7g.large
      - cache.r7g.xlarge
      - cache.r7g.2xlarge
      - cache.r7g.4xlarge
      - cache.r7g.8xlarge
      - cache.r7g.12xlarge
      - cache.r7g.16xlarge

      - cache.r6gd.xlarge
      - cache.r6gd.2xlarge
      - cache.r6gd.4xlarge
      - cache.r6gd.8xlarge
      - cache.r6gd.12xlarge
      - cache.r6gd.16xlarge


  
  SetNumCacheNodes:
    Type: Number
    Description: Redis number of nodes
    Default: 1


Resources:
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: !FindInMap [ClusterNames, !Ref Entorno, Name]
      CacheNodeType: !Ref SetCacheNodeType
      Engine: redis
      NumCacheNodes: !Ref SetNumCacheNodes
      Port: 6379
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      VpcSecurityGroupIds:
        - !Ref RedisSecurityGroup

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis
      SubnetIds: !Ref RedisSubnets

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref RedisVpcId
      GroupDescription: Security group for Redis
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: !Ref CidrIp
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: !Ref CidrIp2


Outputs:
  RedisEndpoint:
    Description: Redis endpoint
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-RedisEndpoint