Mappings:
  S3BucketNames:
    sandbox:
      Name: "s3-storagegw-pagopension-sandbox"
    dev:
      Name: "s3-storagegw-pagopension-dev"
    qa: 
      Name: "s3-storagegw-pagopension-qa"
    prod:
      Name: "s3-storagegw-pagopension-prod"


Parameters:
  Entorno:
    Description: El entorno donde se desplegarán los recursos (sandbox, dev, qa, prod)
    Type: String
    Default: sandbox
    AllowedValues:
      - sandbox
      - dev
      - qa
      - prod

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [S3BucketNames, !Ref Entorno, Name]

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowStorageGatewayAccess
            Effect: Allow
            Principal:
              Service: storagegateway.amazonaws.com
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:ListBucketMultipartUploads
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket]]