apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME} 
  region: us-east-1
  version: "1.27"

privateCluster:
  enabled: false

vpc:
  id: ${VPC_ID}
  subnets:
    private:
      us-east-1b: {id: ${SUBNET_PRIVATE_1B}}
      us-east-1a: {id: ${SUBNET_PRIVATE_1A}}
      us-east-1c: {id: ${SUBNET_PRIVATE_1C}}
    public:
      us-east-1b: {id: ${SUBNET_PUBLIC_1B}}
      us-east-1a: {id: ${SUBNET_PUBLIC_1A}}
      us-east-1c: {id: ${SUBNET_PUBLIC_1C}}


  nat:
    gateway: ${NAT_MODE}
  clusterEndpoints:
    publicAccess: true
    privateAccess: true


fargateProfiles:
  - name: fargateprofile-kubesystem
    selectors:
      - namespace: kube-system
        labels:
          k8s-app: kube-dns

  - name: fargateprofile-elb
    selectors:
      - namespace: kube-system
        labels:
          k8s-elb: elb

  - name: fargateprofile-pagopension
    selectors:
      - namespace: pagopension



cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

    # Sets the number of days to retain the logs for (see [CloudWatch docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax)).
    # By default, log data is stored in CloudWatch Logs indefinitely.
    logRetentionInDays: 7

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true




#review ha
#review oidc