apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-efs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "efs-sc"
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09f65fe81316d211e::fsap-073cd0d2be9f8b44a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-efs-pvc
  namespace: vault
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-sc"
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: vault
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs-storage
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: vault-efs-pvc
